export const AVATAR_SET_PART_PROPERTY = 'AVATAR_SET [PART] [PROPERTY]'; 
export const AVATAR_RESET_PART_PROPERTY = 'AVATAR_RESET [PART] [PROPERTY]'; 
export const AVATAR_RESET_ALL_PROPERTY = 'AVATAR_RESET_ALL_PROPERTIES'; 
